name: Nightly

on:
  schedule:
    - cron:  '0 23 * * *'

jobs:
  reset-sanity-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: oslopride/sanity-mirror-dataset@v0.1.2
        with:
          dataset_to_reset: dev
          dataset_to_mirror: future
          sanity_project_id: 2ger3rla
          sanity_token: ${{ secrets.SANITY_TOKEN }}
